{% set name = "graphistry" %}
{% set version = "0.33.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/graphistry-{{ version }}.tar.gz
  sha256: 40c095ae0ad4143d686b3802495c643a3decb4d663e0038aa6645c06c95d4d0b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - numpy
    - packaging >=20.1
    - palettable >=3.0
    - pandas
    - pyarrow >=0.15.0
    - python >=3.7
    - requests
    - setuptools
    - squarify
    - typing-extensions

test:
  imports:
    - graphistry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/graphistry/pygraphistry
  summary: A visual graph analytics library.
  doc_url: https://pythonhosted.org/graphistry/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
