{% set name = "graphistry" %}
{% set version = "0.25.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/graphistry-{{ version }}.tar.gz
  sha256: d3da426efa6381a1f883caa497044592554f32cecf892d94c16fc1310dec8ff4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - packaging >=20.1
    - pandas >=0.17.0
    - protobuf >=2.6.0
    - pyarrow >=0.15.0
    - python >=3.6
    - requests
    - typing-extensions

test:
  imports:
    - graphistry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/graphistry/pygraphistry
  summary: A visual graph analytics library.
  doc_url: https://pythonhosted.org/graphistry/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
