{% set name = "graphistry" %}
{% set version = "0.28.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/graphistry-{{ version }}.tar.gz
  sha256: 43cec020be01be2665d0939c17509a6b03e34e8dd17dfc0603fe8dba224d1e39

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - packaging >=20.1
    - palettable >=3.0
    - pandas >=0.17.0
    - pyarrow >=0.15.0
    - python >=3.6
    - requests
    - squarify
    - typing-extensions

test:
  imports:
    - graphistry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/graphistry/pygraphistry
  summary: A visual graph analytics library.
  doc_url: https://pythonhosted.org/graphistry/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
