{% set name = "graphistry" %}
{% set version = "0.34.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/graphistry-{{ version }}.tar.gz
  sha256: dee75b2b114604cf707b4d0bc61607929e1b0ca170a5b25406cc4f776802f281

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - python >=3.8
    - numpy
    - packaging >=20.1
    - palettable >=3.0
    - pandas
    - pyarrow >=0.15.0
    - requests
    - setuptools
    - squarify
    - typing_extensions

test:
  imports:
    - graphistry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/graphistry/pygraphistry
  summary: A visual graph analytics library.
  doc_url: https://pythonhosted.org/graphistry/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
