{% set name = "graphistry" %}
{% set version = "0.35.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/graphistry-{{ version }}.tar.gz
  sha256: 315491772982b1ab8a230240f8396e9eee15f57e255c2c1a4adfac2b00e44609

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - packaging >=20.1
    - palettable >=3.0
    - pandas
    - pyarrow >=0.15.0
    - requests
    - setuptools
    - squarify
    - typing_extensions

test:
  imports:
    - graphistry
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/graphistry/pygraphistry
  summary: A visual graph analytics library.
  doc_url: https://pythonhosted.org/graphistry/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
