{% set name = "graphistry" %}
{% set version = "0.23.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/graphistry-{{ version }}.tar.gz
  sha256: 6ef0d31a8a7ea7d30e61d4e31248434b074c8177ff5de42ef6a496a4b60ea279

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - pandas >=0.17.0
    - protobuf >=2.6.0
    - pyarrow >=0.15.0
    - python >=3.6
    - requests

test:
  imports:
    - graphistry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/graphistry/pygraphistry
  summary: A visual graph analytics library.
  doc_url: https://pythonhosted.org/graphistry/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
