schema_version: 1

context:
  name: graphistry
  version: "0.53.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/graphistry-${{ version }}.tar.gz
  sha256: f9c2f09dccd86f9444ac1e68b5f1faadad8bdd51503688907d9587afde2ac2a6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - numpy
    - packaging >=20.1
    - palettable >=3.0
    - pandas
    - pyarrow >=0.15.0
    - requests
    - setuptools
    - squarify
    - typing_extensions
    - lark >=1.1,<2

tests:
  - python:
      imports:
        - graphistry
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A visual graph analytics library.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/graphistry/pygraphistry
  documentation: https://pythonhosted.org/graphistry/

extra:
  recipe-maintainers:
    - thewchan
