schema_version: 1

context:
  name: graphistry
  version: "0.38.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/graphistry-${{ version }}.tar.gz
  sha256: 3686e173ae250baec503574a8d3a48898a0884c0546d9ee5ce5eb57871f6e9bb

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - numpy
    - packaging >=20.1
    - palettable >=3.0
    - pandas
    - pyarrow >=0.15.0
    - requests
    - setuptools
    - squarify
    - typing_extensions

tests:
  - python:
      imports:
        - graphistry
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A visual graph analytics library.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/graphistry/pygraphistry
  documentation: https://pythonhosted.org/graphistry/

extra:
  recipe-maintainers:
    - thewchan
